package com.idemia.tec.jkt.cardiotest.service;

import com.idemia.tec.jkt.cardiotest.controller.RootLayoutController;
import com.idemia.tec.jkt.cardiotest.model.ATR;
import com.idemia.tec.jkt.cardiotest.model.Authentication;
import com.idemia.tec.jkt.cardiotest.model.SecretCodes;
import com.idemia.tec.jkt.cardiotest.model.TestSuite;
import com.idemia.tec.jkt.cardiotest.response.TestSuiteResponse;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.smartcardio.CardException;
import javax.smartcardio.CardTerminal;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

@Service
public class RunServiceImpl implements RunService {

    static Logger logger = Logger.getLogger(RunServiceImpl.class);

    private StringBuilder optionsBuffer;
    private String scriptsDirectory;
    private int exitVal;

    @Autowired
    private RootLayoutController root;
    @Autowired
    private ScriptGeneratorService scriptGenerator;

    @Override
    public TestSuiteResponse runAll() {
        composeScripts();
        runShellCommand("pcomconsole", root.getRunSettings().getProjectPath() + "\\RunAll.pcom");
        // parse result xml
        TestSuite runAllResult = parseRunAllXml();
        if (exitVal == 0) {
            if (runAllResult != null) {
                logger.info(runAllResult.toJson());
                return new TestSuiteResponse(true, "RunAll executed normally", runAllResult);
            } else {
                return new TestSuiteResponse(false, "Failed parsing RunAll output", null);
            }
        }
        else {
            logger.error("Exit value: " + exitVal);
            return new TestSuiteResponse(true, "Some error in execution", runAllResult);
        }
    }

    private void composeScripts() {
        optionsBuffer = new StringBuilder();
        optionsBuffer.append("; Options generated by CardIO Tool on ")
                .append(new Timestamp(System.currentTimeMillis())).append("\n\n");
        StringBuilder runAllBuffer = new StringBuilder();

        createFullStructure();

        // Run All header
        runAllBuffer.append(createRunAllHeader());

        // ATR
        if (root.getRunSettings().getAtr().isIncludeAtr())
            runAllBuffer.append(addAtr(root.getRunSettings().getAtr()));

        // authentication
        if (root.getRunSettings().getAuthentication().isIncludeDeltaTest() || root.getRunSettings().getAuthentication().isIncludeSqnMax())
            runAllBuffer.append(addAuthentication(root.getRunSettings().getAuthentication()));

        // secret codes
        if (root.getRunSettings().getSecretCodes().isInclude3gScript() || root.getRunSettings().getSecretCodes().isInclude2gScript())
            runAllBuffer.append(addSecretCodes(root.getRunSettings().getSecretCodes()));

        runAllBuffer.append(endRunAll());

        // save mappings to file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(scriptsDirectory + "Mapping.txt"))) {
            bw.append(scriptGenerator.generateMapping());
        } catch (IOException e) {
            logger.error("Failed writing mapping file");
        }

        // save options to file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(scriptsDirectory + "Options.txt"))) {
            bw.append(optionsBuffer);
        } catch (IOException e) {
            logger.error("Failed writing options file");
        }

        // save runall to file
        try (BufferedWriter bw = new BufferedWriter(
                new FileWriter(root.getRunSettings().getProjectPath() + "\\RunAll.pcom")
        )) {
            bw.append(runAllBuffer);
        } catch (IOException e) {
//            e.printStackTrace();
            logger.error(e.getMessage());
        }
    }

    private void createFullStructure() {
        // create folder 'scripts'
        scriptsDirectory = root.getRunSettings().getProjectPath() + "\\scripts\\";
        File scriptDir = new File(scriptsDirectory);
        scriptDir.mkdir();

        // copy DLLs
        File dllDir = new File(scriptsDirectory + "dll\\");
        dllDir.mkdir();
        try (Stream<Path> walk = Files.walk(Paths.get("dll"))) {
            List<String> dllFiles = walk.filter(Files::isRegularFile).map(Path::toString).collect(Collectors.toList());
            for (String dll : dllFiles) {
                File sourceDll = new File(dll);
                File targetDll = new File(scriptsDirectory + dll);
                Files.copy(sourceDll.toPath(), targetDll.toPath(), StandardCopyOption.REPLACE_EXISTING);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // copy variable file to project directory
        File sourceVarFile = new File(root.getRunSettings().getAdvSaveVariablesPath());
        File targetVarFile = new File(root.getRunSettings().getProjectPath() + "\\variables.txt");
        try {
            Files.copy(sourceVarFile.toPath(), targetVarFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
//            e.printStackTrace();
            logger.error(e.getMessage() + " - failed copying variable file to project directory");
        }
    }

    private String createRunAllHeader() {
        return "; Generated by CardIO Tool on " + new Timestamp(System.currentTimeMillis()) + "\n\n"
                + "; EP-ID: " + root.getRunSettings().getRequestId() + "\n"
                + "; Request name: " + root.getRunSettings().getRequestName() + "\n"
                + "; Profile name: " + root.getRunSettings().getProfileName() + "\n"
                + "; Version: " + root.getRunSettings().getProfileVersion() + "\n"
                + "; Image Item ID: " + root.getRunSettings().getCardImageItemId() + "\n"
                + "; Customer: " + root.getRunSettings().getCustomer() + "\n"
                + "; Developer: " + root.getRunSettings().getDeveloperName() + "\n"
                + "; Tester: " + root.getRunSettings().getTesterName() + "\n\n"
                + ".LIBRARY_PATH /ADD logs\n"
                + ".LIBRARY_PATH /DISP\n\n";
    }

    private String endRunAll() {
        return ".LIBRARY_PATH /DEL";
    }

    private String addAtr(ATR atr) {
        // add ATR to options
        String optionAtr = "; card parameters\n"
                + ".DEFINE %ATR " + atr.getAtrString() + "\n"
                + "; TCK: " + root.getRunSettings().getAtr().getTck() + "\n\n"
                + ".DEFINE %CARD_MANAGER_AID " + root.getRunSettings().getCardParameters().getCardManagerAid() + "\n\n"
                + ".DEFINE %USIM_AID " + root.getRunSettings().getCardParameters().getUsimAid() + "\n"
                + ".DEFINE %DF_USIM " + root.getRunSettings().getCardParameters().getDfUsim() + "\n\n"
                + ".DEFINE %DF_GSM_AC " + root.getRunSettings().getCardParameters().getDfGsmAccess() + "\n"
                + ".DEFINE %DF_TELECOM " + root.getRunSettings().getCardParameters().getDfTelecom() + "\n\n"
                + ".DEFINE %ISIM_AID " + root.getRunSettings().getCardParameters().getIsimAid() + "\n"
                + ".DEFINE %DF_ISIM " + root.getRunSettings().getCardParameters().getDfIsim() + "\n\n"
                + ".DEFINE %CSIM_AID " + root.getRunSettings().getCardParameters().getCsimAid() + "\n"
                + ".DEFINE %DF_CSIM " + root.getRunSettings().getCardParameters().getDfCsim() + "\n\n";
        optionsBuffer.append(optionAtr);

        // add ATR script to structure
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(scriptsDirectory + "ATR.txt"))) {
            bw.append(scriptGenerator.generateAtr());
        } catch (IOException e) {
            logger.error("Failed writing ATR script");
        }

        return "; ATR\n"
                + ".EXECUTE scripts\\ATR.txt /PATH logs\n"
                + ".ALLUNDEFINE\n\n";
    }

    private String addAuthentication(Authentication authentication) {
        // add Authentication to options
        String optionAuth = "; authentication\n"
                + "; algo parameters:\n"
                + ".SET_BUFFER I %" + authentication.getAkaRi() + "\n"
                + ".DEFINE %R1 I(1:1)\n"
                + ".DEFINE %R2 I(2;1)\n"
                + ".DEFINE %R3 I(3;1)\n"
                + ".DEFINE %R4 I(4;1)\n"
                + ".DEFINE %R5 I(5;1)\n";
        optionsBuffer.append(optionAuth);

        StringBuilder authRunAllString = new StringBuilder();
        authRunAllString.append("; Authentication\n");

        // add authentication script to structure
        if (authentication.isIncludeDeltaTest()) {
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(scriptsDirectory + "Authentication_MILLENAGE_DELTA_TEST.txt"))) {
                bw.append(scriptGenerator.generateMilenageDeltaTest(authentication));
            } catch (IOException e) {
                logger.error("Failed writing MILLENAGE_DELTA_TEST script");
            }
            authRunAllString.append(".EXECUTE scripts\\Authentication_MILLENAGE_DELTA_TEST.txt /PATH logs\n");
            authRunAllString.append(".ALLUNDEFINE\n\n");
        }

        if (authentication.isIncludeSqnMax()) {
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(scriptsDirectory + "Authentication_MILLENAGE_SQN_MAX.txt"))) {
                bw.append(scriptGenerator.generateMilenageSqnMax(authentication));
            } catch (IOException e) {
                logger.error("Failed writing MILLENAGE_SQN_MAX script");
            }
            authRunAllString.append(".EXECUTE scripts\\Authentication_MILLENAGE_SQN_MAX.txt /PATH logs\n");
            authRunAllString.append(".ALLUNDEFINE\n\n");
        }

        return authRunAllString.toString();
    }

    private String addSecretCodes(SecretCodes secretCodes) {
        StringBuilder secretCodesRunAll = new StringBuilder();
        secretCodesRunAll.append("; Secret Codes\n");

        // add secret codes scripts to structure
        if (secretCodes.isInclude3gScript()) {
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(scriptsDirectory + "SecretCodes_3G.txt"))) {
                bw.append(scriptGenerator.generateSecretCodes3g(secretCodes));
            } catch (IOException e) {
                logger.error("Failed writing SecretCodes_3G script");
            }
            secretCodesRunAll.append(".EXECUTE scripts\\SecretCodes_3G.txt /PATH logs\n");
            secretCodesRunAll.append(".ALLUNDEFINE\n\n");
        }

        if (secretCodes.isInclude2gScript()) {
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(scriptsDirectory + "SecretCodes_2G.txt"))) {
                bw.append(scriptGenerator.generateSecretCodes2g(secretCodes));
            } catch (IOException e) {
                logger.error("Failed writing SecretCodes_2G script");
            }
            secretCodesRunAll.append(".EXECUTE scripts\\SecretCodes_2G.txt /PATH logs\n");
            secretCodesRunAll.append(".ALLUNDEFINE\n\n");
        }

        return secretCodesRunAll.toString();
    }

    private TestSuite parseRunAllXml() {
        File runXml = new File(root.getRunSettings().getProjectPath()+ "\\RunAll_L00.xml");
        try {
            JAXBContext jaxbContext = JAXBContext.newInstance(TestSuite.class);
            Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();
            return (TestSuite) unmarshaller.unmarshal(runXml);
        } catch (JAXBException e) {
            e.printStackTrace();
            return null;
        }
    }

    private void launchProcess(List<String> cmdArray) throws IOException, InterruptedException {
        ProcessBuilder processBuilder = new ProcessBuilder(cmdArray);
        processBuilder.redirectErrorStream(true);
        Process process = processBuilder.start();
        exitVal = process.waitFor();
    }

    private void runShellCommand(String pcomExecutable, String scriptName) {
        String readerName = "";
        try {
            List<CardTerminal> terminals = root.getTerminalFactory().terminals().list();
            readerName = terminals.get(root.getRunSettings().getReaderNumber()).getName();
        } catch (CardException e) {
            logger.error(e.getMessage());
//            e.printStackTrace();
        }
        List<String> cmdArray = new ArrayList<>();
        cmdArray.add(pcomExecutable);
        cmdArray.add("-script");
        cmdArray.add(scriptName);
        cmdArray.add("-xmllogpath");
        cmdArray.add(".");
        cmdArray.add("-logpath");
        cmdArray.add(".");
        cmdArray.add("-reader");
        cmdArray.add(readerName);
        cmdArray.add("-protocol");
        cmdArray.add("TPDUMode");
        if (root.getRunSettings().isStopOnError())
            cmdArray.add("-stoponerror");
        try {
            logger.info("Executing.. " + scriptName);
            launchProcess(cmdArray);
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }

    @Override
    public boolean runAtr() {
        composeScripts();
        runShellCommand("pcomconsole", scriptsDirectory + "ATR.txt");
        return exitVal == 0;
    }

    @Override
    public boolean runDeltaTest() {
        composeScripts();
        runShellCommand("pcomconsole", scriptsDirectory + "Authentication_MILLENAGE_DELTA_TEST.txt");
        return exitVal == 0;
    }

    @Override
    public boolean runSqnMax() {
        composeScripts();
        runShellCommand("pcomconsole", scriptsDirectory + "Authentication_MILLENAGE_SQN_MAX.txt");
        return exitVal == 0;
    }

    @Override
    public boolean runSecretCodes3g() {
        composeScripts();
        runShellCommand("pcomconsole", scriptsDirectory + "SecretCodes_3G.txt");
        return exitVal == 0;
    }

    @Override
    public boolean runSecretCodes2g() {
        composeScripts();
        runShellCommand("pcomconsole", scriptsDirectory + "SecretCodes_2G.txt");
        return exitVal == 0;
    }

}
